In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
df = pd.read_csv("Social_Network_Ads.csv")
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [3]:
x = df[['Age','EstimatedSalary']]
y = df ['Purchased']

In [4]:
from sklearn.linear_model import LogisticRegression

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [27]:
LReg = LogisticRegression ()
LReg.fit(x_train,y_train)

LogisticRegression()

In [28]:
prediction_test = LReg.predict(x_test)
prediction_train = LReg.predict(x_train)

In [19]:
prediction_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, prediction_test)
print(cm)
accuracy_score(y_test, prediction_test)

[[58  0]
 [22  0]]


0.725

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,prediction_test)
print(cm)
accuracy_score(y_test,prediction_test)

[[58  0]
 [22  0]]


0.725